{% set name = "safe-rm" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://launchpad.net/safe-rm/trunk/{{ version }}/+download/safe-rm-{{ version }}.tar.gz
  sha256: a1c916894c5b70e02a6ec6c33abbb2c3b3827464cffd4baffd47ffb69a56a1e0

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - 'safe-rm 2>&1 | grep -q "usage: rm \[-f | -i\] \[-dIPRrvWx\] file"'  # [osx]
    - 'safe-rm 2>&1 | grep -q "rm: missing operand"'  # [linux]

about:
  home: https://launchpad.net/safe-rm
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - THIRDPARTY.yml
  summary: Wraps rm to prevent dangerous deletion of files
  dev_url: https://launchpad.net/safe-rm

extra:
  recipe-maintainers:
    - danielnachun
