context:
  version: 1.1.0

package:
  name: safe-rm
  version: ${{ version }}

source:
  url: https://launchpad.net/safe-rm/trunk/${{ version }}/+download/safe-rm-${{ version }}.tar.gz
  sha256: a1c916894c5b70e02a6ec6c33abbb2c3b3827464cffd4baffd47ffb69a56a1e0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - if: osx
        then: "safe-rm 2>&1 | grep -q \"usage: rm \\[-f | -i\\] \\[-dIPRrvWx\\] file\""
      - if: linux
        then: "safe-rm 2>&1 | grep -q \"rm: missing operand\""

about:
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - THIRDPARTY.yml
  summary: Wraps rm to prevent dangerous deletion of files
  homepage: https://launchpad.net/safe-rm
  repository: https://launchpad.net/safe-rm

extra:
  recipe-maintainers:
    - danielnachun
